# This is a basic workflow to help you get started with Actions

name: Build_Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - name: Install Module
        run: pip install -r requirements.txt
        
      - name: Test Crawler
        run: pytest ./Test/testCrawling
