# This is a basic workflow to help you get started with Actions

name: Build_Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Module
        run: pip install requirements.txt
      - name: Test Crawler
        run: pytest ./Test/testCrawling
